services:
  invoice:
    image: invoice
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://database-mssql:1433;database=invoice;encrypt=false
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://database-mssql:1433;database=invoice;encrypt=false
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8082/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      database-mssql:
        condition: service_healthy
  
  notification:
    image: notification
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://database-mssql:1433;database=notification;encrypt=false
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://database-mssql:1433;database=notification;encrypt=false
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8083/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      database-mssql:
        condition: service_healthy

  product:
    image: product
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_DATASOURCE_URL=jdbc:sqlserver://database-mssql:1433;database=product;encrypt=false
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://database-mssql:1433;database=product;encrypt=false
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8081/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      database-mssql:
        condition: service_healthy

  store:
    image: store
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,api-docs
      - MANAGEMENT_PROMETHEUS_METRICS_EXPORT_ENABLED=true
      - SPRING_CLOUD_CONSUL_HOST=consul
      - SPRING_CLOUD_CONSUL_PORT=8500
      - SPRING_R2DBC_URL=r2dbc:mssql://database-mssql:1433/store
      - SPRING_LIQUIBASE_URL=jdbc:sqlserver://database-mssql:1433;database=store;encrypt=false
    ports:
      - 8083:8080
    healthcheck:
      test:
        - CMD
        - curl
        - -f
        - http://localhost:8080/management/health
      interval: 5s
      timeout: 5s
      retries: 40
    depends_on:
      database-mssql:
        condition: service_healthy

  database-mssql:
    image: mcr.microsoft.com/mssql/server:2019-CU16-GDR1-ubuntu-20.04
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_PID=Express
      - SA_PASSWORD=yourStrong(!)Password
      - MSSQL_DATABASE=master
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=yourStrong(!)Password
      - MSSQL_SLEEP=15
    command: /bin/bash -c '/opt/mssql/bin/sqlservr & echo "wait $$MSSQL_SLEEP sec for DB to start "; sleep $$MSSQL_SLEEP; /opt/mssql-tools/bin/sqlcmd -U $$MSSQL_USER -P $$MSSQL_PASSWORD -d tempdb -q "CREATE DATABASE invoice; CREATE DATABASE notification; CREATE DATABASE product; CREATE DATABASE store;"; wait;'
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$${SA_PASSWORD}" -Q "USE $${MSSQL_DATABASE}" -b -o /dev/null
      interval: 10s
      timeout: 3s
      retries: 10
      start_period: 10s
    ports:
      - 1435:1433

  consul:
    image: docker.io/bitnami/consul:1.20.1
    ports:
      - 8300:8300
      - 8500:8500
      - 8600:8600
    command: consul agent -dev -ui -client 0.0.0.0 -log-level=INFO
  consul-config-loader:
    image: jhipster/consul-config-loader:v0.4.1
    volumes:
      - ./central-server-config:/config
    environment:
      - INIT_SLEEP_SECONDS=5
      - CONSUL_URL=consul
      - CONSUL_PORT=8500
