package com.jhipster.demo.invoice.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ShipmentAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAllPropertiesEquals(Shipment expected, Shipment actual) {
        assertShipmentAutoGeneratedPropertiesEquals(expected, actual);
        assertShipmentAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAllUpdatablePropertiesEquals(Shipment expected, Shipment actual) {
        assertShipmentUpdatableFieldsEquals(expected, actual);
        assertShipmentUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentAutoGeneratedPropertiesEquals(Shipment expected, Shipment actual) {
        assertThat(expected)
            .as("Verify Shipment auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentUpdatableFieldsEquals(Shipment expected, Shipment actual) {
        assertThat(expected)
            .as("Verify Shipment relevant properties")
            .satisfies(e -> assertThat(e.getTrackingCode()).as("check trackingCode").isEqualTo(actual.getTrackingCode()))
            .satisfies(e -> assertThat(e.getDate()).as("check date").isEqualTo(actual.getDate()))
            .satisfies(e -> assertThat(e.getDetails()).as("check details").isEqualTo(actual.getDetails()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertShipmentUpdatableRelationshipsEquals(Shipment expected, Shipment actual) {
        assertThat(expected)
            .as("Verify Shipment relationships")
            .satisfies(e -> assertThat(e.getInvoice()).as("check invoice").isEqualTo(actual.getInvoice()));
    }
}
